---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sisjurco/sistctrljur/
    - export DEPLOYPATH_JS=/home/sisjurco/public_html/js/
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R bootstrap $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R database $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R public/js/datatables $DEPLOYPATH_JS
    - /bin/cp public/js/app.js $DEPLOYPATH_JS
    - /bin/cp public/js/bCrypt.js $DEPLOYPATH_JS
    - /bin/cp public/js/showPDFjs_tipo_1.js $DEPLOYPATH_JS
    - /bin/cp public/js/showPDFjs_tipo_2.js $DEPLOYPATH_JS
    - /bin/cp public/js/showPDFjs_tipo_3.js $DEPLOYPATH_JS
    - /bin/cp public/js/Upload.js $DEPLOYPATH_JS
    - /bin/cp public/js/UploadCreate.js $DEPLOYPATH_JS
